version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Data Source=/app/data/tasks.db
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      # These are also set in the Dockerfile; keeping here for clarity/override
      VITE_GRAPHQL_HTTP_URL: http://localhost:8080/graphql
      VITE_GRAPHQL_WS_URL: ws://localhost:8080/graphql
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      # Live-reload: mount your source; keep node_modules inside the container
      - ./frontend:/app
      - /app/node_modules